name: Greetings
env:
  scope: Workflow
  company: LNRSTest
on: 
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      company:
        description: 'Company Name'
        required: true
        default: LNRSTest

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
        run: |
          echo ${{github.event.inputs.company}}
          echo ${{secrets.MY_SECRET}}
          echo ${{env.scope}}
          echo ${{env.company}}
